name: CI

on:
  # Triggers the workflow on any pull request and push to develop
  push:
    branches: [ develop ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Common cache
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Common setup
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Selection of MatrixSDK
      - uses: nelonoel/branch-name@v1.0.1
      - name: Extract branch name
        shell: sh
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - name: Use the pending release of MatrixSDK ${{ github.event.inputs.from_branch }}
        if: startsWith(github.event.inputs.from_branch, 'release/')
        run: |
          echo 'branch  ${{ github.event.inputs.from_branch }}'
          echo ${BRANCH_NAME}
          bundle exec fastlane point_sample_app_to_pending_releases
      - name: Use the same feature branch of MatrixSDK
        if: startsWith(github.event.inputs.from_branch, 'release/') != true
        run: |
          echo 'branch  ${{ github.event.inputs.from_branch }}'
          echo ${BRANCH_NAME}
          bundle exec fastlane point_sample_app_to_same_feature

      # Main step
      - name: Build iOS simulator
        run: bundle exec fastlane build_sample_app


  tests:
    name: Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Common cache
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Common setup
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
   
      - name: Use right MatrixSDK versions
        run: bundle exec fastlane point_sample_app_to_pending_releases

      # Main step
      - name: Unit tests
        run: bundle exec fastlane test

  cocoapods:
    name: CocoaPods
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Common cache
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Common setup
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Use right MatrixSDK versions
        run: bundle exec fastlane point_podspec_to_pending_releases

      # Main step
      - name: Lint MatrixKit.podspec
        run: bundle exec fastlane lint_local_pod_MatrixKit
